apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: flaskapp
    matchExpressions:
      - {key: tier, operator: In, values: [flaskapp]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: hello-python:v4
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        env:
        - name: GET_HOSTS_FROM
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          value: env
        ports:
        - containerPort: 8080
