apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: flaskapp
        image: hello-python:v5
        ports:
        - containerPort: 8080
